const thirdModalConfig = {
  defensive: {
    borderColor: "border-sky-500/60",
    shadowColor: "shadow-[0_0_70px_rgba(0,150,255,0.7)]",
    accentColor: "border-sky-500",
    titleId: "defensive-modal-title",
    highlightClass: "text-sky-400",
    buttonClass: "bg-sky-600 hover:bg-sky-700",
    title: "DEFENSIVE THIRD",
    intro: "The",
    name: "Defensive Third",
    nameEnd: "is the area closest to your own goal.",
    bullets: ["Focus on defending and preventing goals", "Compact shape and organization", "Quick transitions to attack", "Goalkeeper communication is crucial", "Clear the ball under pressure", "Stay connected as a unit"],
    quote: "Build from the back, stay organized, and follow the rules.",
  },
  mid: {
    borderColor: "border-green-500/60",
    shadowColor: "shadow-[0_0_70px_rgba(0,255,150,0.7)]",
    accentColor: "border-green-500",
    titleId: "mid-modal-title",
    highlightClass: "text-green-400",
    buttonClass: "bg-green-600 hover:bg-green-700",
    title: "MID THIRD",
    intro: "The",
    name: "Mid Third",
    nameEnd: "is the central area of the field, also known as the midfield.",
    bullets: ["Transition between defense and attack", "Control possession and tempo", "Connect defense to forwards", "Win second balls and duels", "Dictate the flow of the game", "Support both attacking and defending"],
    quote: "Control the midfield, control the game. Follow the rules.",
  },
  attacking: {
    borderColor: "border-red-500/60",
    shadowColor: "shadow-[0_0_70px_rgba(255,100,100,0.7)]",
    accentColor: "border-red-500",
    titleId: "attacking-modal-title",
    highlightClass: "text-red-400",
    buttonClass: "bg-red-600 hover:bg-red-700",
    title: "ATTACKING THIRD",
    intro: "The",
    name: "Attacking Third",
    nameEnd: "is the area closest to the opponent's goal.",
    bullets: ["Create scoring opportunities", "Final passes and crosses", "Take risks and be creative", "Finish chances on goal", "Combine with teammates in tight spaces", "Be unpredictable and decisive"],
    quote: "No rules! Express yourself and score goals.",
  },
} as const;

export { thirdModalConfig };
